Rename jitsi meet to qiscus meet
rajapulau/react-native-jitsi-meet-1 pull request #1
Opened 2020-10-31 06:27 UTC by mazsam

2020-11-04 07:18 UTC, rajapulau requested changes
Mas @mazsam ini ada 2 review dari aq ya

2020-11-04 07:18 UTC, rajapulau commented on ExampleApp/App.js
> +import QiscusMeet, { QiscusMeetView } from 'react-native-jitsi-meet';
mas @mazsam `react-native-jitsi-meet` ini bisa digantikan sekalian ke `react-native-qiscus-meet` ?

2020-11-04 07:18 UTC, rajapulau commented on ExampleApp/App.js
> +      const url = 'https://meet.jit.si/testmeet';
ini mending sama jangan pakai default URL dari jitsi mas @mazsam . Pakai url dari qiscus saja

2020-11-04 07:24 UTC, mazsam commented on ExampleApp/App.js
> +import QiscusMeet, { QiscusMeetView } from 'react-native-jitsi-meet';
Bisa mas, ini tegantung penamaan package di package.json nya.

2020-11-04 07:25 UTC, mazsam commented on ExampleApp/App.js
> +      const url = 'https://meet.jit.si/testmeet';
Oke mas, sekalian aku kasih di QiscusMeet.setup nanti.

2020-11-05 04:33 UTC, rajapulau requested changes

2020-11-05 04:33 UTC, rajapulau commented on ExampleApp/App.js
> +    const url = 'https://meet.qiscus.com/testmeet';
mas @mazsam ini harusnya `https://meet.qiscus.com/` untuk nama room itu dimasukkan dalam `userInfo` aja mas

2020-11-05 04:33 UTC, rajapulau commented on ExampleApp/App.js
> +    QiscusMeet.audioCall(userInfo);
Karena ini untuk seragam di SDK lain. untuk audio bisa dibuat seperti ini gak mas?

```
const userInfo = {
      displayName: 'Meet User',
      email: 'user@qiscus.net',
      avatar: 'https:/gravatar.com/avatar/abc123',
      videoMuted : true,
      audioMuted : false
};

QiscusMeet.call(userInfo);
```

2020-11-06 06:29 UTC, rajapulau approved these changes

2020-11-06 06:30 UTC, merged